version: '3.8'

services:
  cadvisor-snmp:
    build: .
    container_name: cadvisor-snmp-bridge
    restart: unless-stopped
    # Host networking - requires privileged mode to bind to port 161
    network_mode: host
    privileged: true
    environment:
      # URL to your cAdvisor instance
      - CADVISOR_URL=http://localhost:8080
      # SNMP read-only community string (change this!)
      - SNMP_COMMUNITY=public
    volumes:
      # Mount config directory - config file will be generated here
      - ./config:/app/config:rw

